### ISSUE TITLE
url shortening - url whitelisting

### ISSUE THREAD

**Issue by lp-tattwell** [LivePersonInc/developer-center#729] opened 2020-05-26 15:27 UTC
There is some inconsistency with the documents for URL shortening.

[link 1](https://developers.liveperson.com/conversation-builder-interactions-interaction-basics.html#url-shortening)
Documentation says URL needs whitelisting, however, the feature works perfectly fine without any whitelisting. Is this correct?

[link 2](https://developers.liveperson.com/conversation-builder-bots-bot-basics.html#configure-bot-settings)
The above doc says the url _might_ need whitelisting.

[link 3](https://knowledge.liveperson.com/release-notes-2020-march-week-of-march-23rd.html#conversation-builder---url-shortening)
The above doc says you need to whitelist and then links to FaaS whitelisting which I am sure is not correct. 

Also, none of the documents say that query params on the end of URLs are not shortened so you shouldn't use the feature if your link has many params on the end.

**Comment by j9t** [comment] 2022-07-11 09:22
Thanks for filing this, @lp-tattwell, and the patience. @itay1313, can you have a look, and perhaps identify contacts to clarify (at least for links 1 and 2)?

**Comment by mferreira-lp** [comment] 2022-07-12 15:27
Hi @j9t , this falls within the Conversational AI space, so I am looking into this today. I just sent an inquiry to the CB team for follow-up and am waiting to hear back. The 3rd link/item is no longer relevant since -- when the Knowledge Center was ported from GitHub to the Kontent CMS, not all of the release notes were ported over. So the release note in question no longer is available. 

@itay1313 , you can assign this one to me.

**Comment by j9t** [comment] 2022-07-12 16:10
Thanks @mferreira-lp!

**Comment by mferreira-lp** [comment] 2022-08-01 12:56
Hi @lp-tattwell , just an update on this. The team has recently confirmed that whitelisting isn't required in this case, as you indicate. The UI and documentation will be updated in the next release. Thank you for raising this.

**Comment by lp-tattwell** [comment] 2022-08-01 13:09
No worries at all, happy to help.

Just for my own knowledge, what kind of cadence are the releases? Is there a set release schedule?

**Comment by j9t** [comment] 2022-08-31 09:30
(Following up on this internally.)

**Comment by mferreira-lp** [comment] 2022-08-31 12:10
The internal ticket for this item is BA-13092. cc @lp-tattwell, @j9t

**Comment by j9t** [comment] 2022-08-31 12:59
Thank you! (Closing this one.)

**Closed by j9t** 2022-08-31 12:59 UTC
